import { getStripe } from '@/lib/stripe'
import config from '@/payload.config'
import { NextRequest, NextResponse } from 'next/server'
import { getPayload } from 'payload'

/* ═══════════════════════════════════════════════════════════════
 *  GET /api/voucher/confirm?session_id=cs_xxx
 *  GET /api/voucher/confirm?payment_intent=pi_xxx
 *
 *  Called from the success page after Stripe redirects back, or
 *  after inline PaymentElement confirmation.
 *  Verifies the payment, creates a generic Voucher record in
 *  Payload, and sends the voucher email via Brevo.
 *
 *  Idempotent: if a voucher already exists for this session, it
 *  returns the existing voucher instead of creating a duplicate.
 * ═══════════════════════════════════════════════════════════════ */

export async function GET(request: NextRequest) {
  try {
    const sessionId = request.nextUrl.searchParams.get('session_id')
    const paymentIntentId = request.nextUrl.searchParams.get('payment_intent')

    if (!sessionId && !paymentIntentId) {
      return NextResponse.json(
        { success: false, error: 'Missing session_id or payment_intent parameter.' },
        { status: 400 },
      )
    }

    let meta: Record<string, string> = {}
    let _paymentStatus: string = ''
    let idempotencyKey: string = ''

    if (sessionId) {
      // ─── Verify via Stripe Checkout Session ─────────────────────

      let session
      try {
        session = await getStripe().checkout.sessions.retrieve(sessionId)
      } catch (_err) {
        return NextResponse.json(
          { success: false, error: 'Invalid checkout session.' },
          { status: 400 },
        )
      }

      if (session.payment_status !== 'paid') {
        return NextResponse.json(
          { success: false, error: 'Payment has not been completed.' },
          { status: 402 },
        )
      }

      if (session.metadata?.type !== 'voucher_purchase') {
        return NextResponse.json(
          { success: false, error: 'This session is not a voucher purchase.' },
          { status: 400 },
        )
      }

      meta = session.metadata as Record<string, string>
      _paymentStatus = session.payment_status
      idempotencyKey = sessionId
    } else {
      // ─── Verify via Stripe PaymentIntent ────────────────────────

      let paymentIntent
      try {
        paymentIntent = await getStripe().paymentIntents.retrieve(paymentIntentId!)
      } catch (_err) {
        return NextResponse.json(
          { success: false, error: 'Invalid payment intent.' },
          { status: 400 },
        )
      }

      if (paymentIntent.status !== 'succeeded') {
        return NextResponse.json(
          { success: false, error: 'Payment has not been completed.' },
          { status: 402 },
        )
      }

      if (paymentIntent.metadata?.type !== 'voucher_purchase') {
        return NextResponse.json(
          { success: false, error: 'This payment is not a voucher purchase.' },
          { status: 400 },
        )
      }

      meta = paymentIntent.metadata as Record<string, string>
      _paymentStatus = paymentIntent.status
      idempotencyKey = paymentIntentId!
    }

    // ─── Idempotency: Check if voucher already exists ────────────

    const payload = await getPayload({ config })

    const existing = await payload.find({
      collection: 'vouchers',
      where: { stripeSessionId: { equals: idempotencyKey } },
      limit: 1,
      overrideAccess: true,
    })

    if (existing.docs.length > 0) {
      const existingVoucher = existing.docs[0]
      return NextResponse.json({
        success: true,
        voucher: {
          code: existingVoucher.code,
          value: existingVoucher.value,
          deliveryMethod: existingVoucher.deliveryMethod,
          recipientEmail: existingVoucher.recipientEmail || null,
        },
      })
    }

    // ─── Create Voucher Record ───────────────────────────────────

    const voucher = await payload.create({
      collection: 'vouchers',
      overrideAccess: true,
      draft: false,
      data: {
        // code is auto-generated by beforeChange hook
        code: '',
        value: Number(meta.amount),
        status: 'active',
        purchaserName: meta.purchaserName || undefined,
        purchaserEmail: meta.purchaserEmail,
        recipientName: meta.recipientName || undefined,
        recipientEmail: meta.recipientEmail || undefined,
        personalNote: meta.personalNote || undefined,
        deliveryMethod:
          (meta.deliveryMethod as 'email-recipient' | 'email-self' | 'pdf' | 'email' | 'pickup') ||
          'email-self',
        stripeSessionId: idempotencyKey,
        redeemed: false,
      },
    })

    payload.logger.info(
      `[voucher/confirm] Created voucher ${voucher.code} for key ${idempotencyKey}`,
    )

    // ─── Email will be sent automatically via afterChange hook ─────

    return NextResponse.json({
      success: true,
      voucher: {
        code: voucher.code,
        value: Number(meta.amount),
        deliveryMethod: voucher.deliveryMethod,
        recipientEmail: voucher.recipientEmail || null,
      },
    })
  } catch (error) {
    console.error('[voucher/confirm] Error:', error)
    return NextResponse.json(
      { success: false, error: 'An unexpected error occurred.' },
      { status: 500 },
    )
  }
}
