import { BREVO_TEMPLATES, sendTemplateEmail } from '@/lib/brevo'
import { stripe } from '@/lib/stripe'
import configPromise from '@payload-config'
import { NextRequest, NextResponse } from 'next/server'
import { getPayload } from 'payload'

/* ═══════════════════════════════════════════════════════════════
 *  GET /api/voucher/confirm?session_id=cs_xxx
 *
 *  Called from the success page after Stripe redirects back.
 *  Verifies the payment, creates a generic Voucher record in
 *  Payload, and sends the voucher email via Brevo.
 *
 *  Idempotent: if a voucher already exists for this session, it
 *  returns the existing voucher instead of creating a duplicate.
 * ═══════════════════════════════════════════════════════════════ */

export async function GET(request: NextRequest) {
  try {
    const sessionId = request.nextUrl.searchParams.get('session_id')

    if (!sessionId || typeof sessionId !== 'string') {
      return NextResponse.json(
        { success: false, error: 'Missing session_id parameter.' },
        { status: 400 },
      )
    }

    // ─── Verify Stripe Session ───────────────────────────────────

    let session
    try {
      session = await stripe.checkout.sessions.retrieve(sessionId)
    } catch (_err) {
      return NextResponse.json(
        { success: false, error: 'Invalid checkout session.' },
        { status: 400 },
      )
    }

    if (session.payment_status !== 'paid') {
      return NextResponse.json(
        { success: false, error: 'Payment has not been completed.' },
        { status: 402 },
      )
    }

    if (session.metadata?.type !== 'voucher_purchase') {
      return NextResponse.json(
        { success: false, error: 'This session is not a voucher purchase.' },
        { status: 400 },
      )
    }

    // ─── Idempotency: Check if voucher already exists ────────────

    const config = await configPromise
    const payload = await getPayload({ config })

    const existing = await payload.find({
      collection: 'vouchers',
      where: { stripeSessionId: { equals: sessionId } },
      limit: 1,
      overrideAccess: true,
    })

    if (existing.docs.length > 0) {
      const existingVoucher = existing.docs[0]
      return NextResponse.json({
        success: true,
        voucher: {
          code: existingVoucher.code,
          value: existingVoucher.value,
          deliveryMethod: existingVoucher.deliveryMethod,
          recipientEmail: existingVoucher.recipientEmail || null,
        },
      })
    }

    // ─── Create Voucher Record ───────────────────────────────────

    const meta = session.metadata
    const voucher = await payload.create({
      collection: 'vouchers',
      overrideAccess: true,
      draft: false,
      data: {
        // code is auto-generated by beforeChange hook
        code: '',
        value: Number(meta.amount),
        status: 'active',
        purchaserEmail: meta.purchaserEmail,
        recipientEmail: meta.recipientEmail || undefined,
        deliveryMethod: (meta.deliveryMethod as 'email' | 'pickup') || 'email',
        stripeSessionId: sessionId,
        redeemed: false,
      },
    })

    payload.logger.info(
      `[voucher/confirm] Created voucher ${voucher.code} for session ${sessionId}`,
    )

    // ─── Send Email Notification ─────────────────────────────────

    try {
      await sendTemplateEmail({
        to: [{ email: meta.purchaserEmail }],
        templateId: BREVO_TEMPLATES.VOUCHER_PURCHASED,
        params: {
          VOUCHER_CODE: voucher.code,
          VOUCHER_VALUE: `\u20AC${meta.amount}`,
          PURCHASER_NAME: meta.purchaserEmail,
          DELIVERY_METHOD: meta.deliveryMethod === 'email' ? 'E-Mail' : 'Abholung',
        },
      })

      // If email delivery and recipient email exists, also email recipient
      if (
        meta.deliveryMethod === 'email' &&
        meta.recipientEmail &&
        meta.recipientEmail !== meta.purchaserEmail
      ) {
        await sendTemplateEmail({
          to: [{ email: meta.recipientEmail }],
          templateId: BREVO_TEMPLATES.VOUCHER_PURCHASED,
          params: {
            VOUCHER_CODE: voucher.code,
            VOUCHER_VALUE: `\u20AC${meta.amount}`,
            PURCHASER_NAME: 'Jemand Besonderes',
            DELIVERY_METHOD: 'E-Mail',
          },
        })
      }
    } catch (emailErr) {
      payload.logger.error(
        `[voucher/confirm] Email failed for voucher ${voucher.code}: ${emailErr instanceof Error ? emailErr.message : String(emailErr)}`,
      )
    }

    return NextResponse.json({
      success: true,
      voucher: {
        code: voucher.code,
        value: Number(meta.amount),
        deliveryMethod: voucher.deliveryMethod,
        recipientEmail: voucher.recipientEmail || null,
      },
    })
  } catch (error) {
    console.error('[voucher/confirm] Error:', error)
    return NextResponse.json(
      { success: false, error: 'An unexpected error occurred.' },
      { status: 500 },
    )
  }
}
