import { NextRequest, NextResponse } from 'next/server'

import { getAdminRecipients } from '@/lib/adminNotification'
import { BREVO_TEMPLATES, sendTemplateEmail, sendTransactionalEmail } from '@/lib/brevo'
import { cancelReasonLabel, loadFreshForMutation, logActivityEvent, updateSeat } from '@/lib/manageBooking'

/* ═══════════════════════════════════════════════════════════════
 *  POST /api/manage-booking/[token]/rebook-later
 *  body: { seatIndex: number, reason: string }
 *
 *  REBOOK_LATER_VIA_CODE — issues a Vouchers row with
 *  origin: 'cancellation-self-service' (12-month deferred rebooking
 *  code, NOT a paid gift card). Consumes the seat's one-time
 *  rebooking right (AGB §4.6).
 *
 *  Deliberately calls payload.create with
 *  context.skipVoucherEmail:true — Vouchers.afterChange
 *  (sendVoucherPurchaseEmail) sends "thank you for your purchase" copy
 *  that is flatly wrong here (no money changed hands, nothing was
 *  bought). This route sends its own VOUCHER_CODE_ISSUED email instead.
 * ═══════════════════════════════════════════════════════════════ */

export async function POST(request: NextRequest, { params }: { params: Promise<{ token: string }> }) {
  const { token } = await params

  let body: { seatIndex?: unknown; reason?: unknown }
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ success: false, error: 'Invalid JSON body' }, { status: 400 })
  }

  const seatIndex = typeof body.seatIndex === 'number' ? body.seatIndex : NaN
  const reason = typeof body.reason === 'string' ? body.reason : 'other'

  if (!Number.isInteger(seatIndex) || seatIndex < 0) {
    return NextResponse.json({ success: false, error: 'Invalid seatIndex' }, { status: 400 })
  }

  const loaded = await loadFreshForMutation(token, seatIndex)
  if (loaded.error) {
    const status = loaded.error === 'expired' ? 410 : 404
    return NextResponse.json({ success: false, error: loaded.error }, { status })
  }

  const { payload, booking, bundle } = loaded

  if (!bundle.options.includes('REBOOK_LATER_VIA_CODE')) {
    return NextResponse.json(
      {
        success: false,
        error: 'action_not_allowed',
        message: 'Rebooking via code is no longer available for this seat.',
      },
      { status: 409 },
    )
  }

  const pricePerPerson = typeof booking.pricePerPerson === 'number' ? booking.pricePerPerson : 99

  const voucher = await payload.create({
    collection: 'vouchers',
    draft: false,
    data: {
      code: '', // auto-generated by Vouchers' beforeValidate hook
      value: pricePerPerson,
      origin: 'cancellation-self-service',
      status: 'active',
      purchaserName: [booking.firstName, booking.lastName].filter(Boolean).join(' ') || undefined,
      purchaserEmail: booking.email || undefined,
      deliveryMethod: 'email-self',
      notes: `Storno-Gutschein — ursprüngliche Buchung ${booking.id}, Platz ${seatIndex + 1}. Grund: ${cancelReasonLabel(reason)}`,
    },
    context: { skipVoucherEmail: true, skipRevalidate: true, disableRevalidate: true },
    overrideAccess: true,
  })

  const now = new Date().toISOString()
  await updateSeat(payload, booking, seatIndex, {
    seatStatus: 'voucher_issued',
    selfRebookingUsed: true,
    cancelledAt: now,
    cancelledReason: reason,
    linkedVoucherId: voucher.id,
  })

  await logActivityEvent(
    payload,
    'booking_rebooked',
    String(booking.id),
    `${booking.firstName ?? 'Gast'} ${booking.lastName ?? ''} — ${booking.workshopTitle}, Platz ${seatIndex + 1}: Gutschein-Code für spätere Umbuchung ausgestellt (${voucher.code})`.trim(),
  )

  // ─── Customer email with the code (best-effort) ───────────────────
  if (booking.email) {
    const expiry = new Date()
    expiry.setFullYear(expiry.getFullYear() + 1)
    await sendTemplateEmail({
      to: [{ email: booking.email, name: booking.firstName ?? undefined }],
      templateId: BREVO_TEMPLATES.VOUCHER_CODE_ISSUED,
      params: {
        FIRST_NAME: booking.firstName || 'Gast',
        VOUCHER_CODE: String(voucher.code ?? ''),
        VOUCHER_AMOUNT: String(pricePerPerson),
        VOUCHER_EXPIRY: expiry.toLocaleDateString('de-AT'),
        WORKSHOP_TITLE: String(booking.workshopTitle ?? ''),
      },
    })
  }

  // ─── Admin alert (best-effort) ─────────────────────────────────────
  try {
    const htmlContent = `
<h2 style="font-family:sans-serif;margin-bottom:16px">Umbuchungs-Code ausgestellt: ${String(voucher.code ?? '')}</h2>
<table style="font-family:sans-serif;border-collapse:collapse;font-size:14px">
  <tr><td style="padding:4px 12px 4px 0;color:#555">Kund:in</td><td style="padding:4px 0">${booking.firstName ?? ''} ${booking.lastName ?? ''} ${booking.email ? `&lt;${booking.email}&gt;` : ''}</td></tr>
  <tr><td style="padding:4px 12px 4px 0;color:#555">Ursprünglicher Workshop</td><td style="padding:4px 0">${booking.workshopTitle} · ${booking.date} ${booking.time}</td></tr>
  <tr><td style="padding:4px 12px 4px 0;color:#555">Platz</td><td style="padding:4px 0">${seatIndex + 1}</td></tr>
  <tr><td style="padding:16px 12px 4px 0;color:#555;border-top:1px solid #eee">Code</td><td style="padding:16px 0 4px;border-top:1px solid #eee;font-family:monospace">${voucher.code}</td></tr>
</table>`
    await sendTransactionalEmail({
      to: getAdminRecipients(),
      subject: `Umbuchungs-Code ausgestellt: ${String(voucher.code ?? '')}`,
      htmlContent,
    })
  } catch (err) {
    payload.logger.error(
      `[manage-booking] Failed to send admin alert for rebook-later voucher ${voucher.id}: ${err instanceof Error ? err.message : String(err)}`,
    )
  }

  return NextResponse.json({ success: true, voucherCode: voucher.code })
}
