/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'de' | 'en';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (string | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (string | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (string | null) | User;
  customerEmail?: string | null;
  transactions?: (string | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: string | Media;
        variantOption?: (string | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (string | VariantType)[] | null;
  variants?: {
    docs?: (string | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  relatedProducts?: (string | Product)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  categories?: (string | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: string;
  _variantOptions_options_order?: string | null;
  variantType: string | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: string;
  label: string;
  name: string;
  options?: {
    docs?: (string | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  publishedOn?: string | null;
  hero: {
    type:
      | 'none'
      | 'highImpact'
      | 'mediumImpact'
      | 'lowImpact'
      | 'heroSlider'
      | 'heroCarousel'
      | 'foodPresentationSlider';
    /**
     * Small uppercase text above the heading (e.g. "Fermentation for everyone").
     */
    eyebrow?: string | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Display the gold FERMENTFREUDE wordmark above the heading in the hero section.
     */
    showWordmark?: boolean | null;
    /**
     * Social media icons displayed alongside the hero content. Leave empty to hide.
     */
    socialLinks?:
      | {
          platform: 'facebook' | 'twitter' | 'instagram' | 'pinterest' | 'youtube' | 'tiktok';
          /**
           * Full URL to your social media profile (e.g. https://facebook.com/yourpage).
           */
          url: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Images for the hero carousel. Add 3–5 for the best visual effect. They appear in a stacked slider layout.
     */
    heroImages?:
      | {
          image: string | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Each slide has its own text, product images, colors, and CTA. The slider cycles through these automatically.
     */
    heroSlides?:
      | {
          /**
           * Internal ID for this slide (e.g. "lakto", "kombucha", "tempeh", "basics"). Not shown to visitors.
           */
          slideId: string;
          /**
           * Small uppercase text above the title (e.g. "Workshop Experience").
           */
          eyebrow?: string | null;
          /**
           * Main heading for this slide. Use \n for line breaks.
           */
          title: string;
          /**
           * Short description text below the title.
           */
          description?: string | null;
          /**
           * Short tags displayed below the divider (e.g. "All-natural", "Probiotic-rich").
           */
          attributes?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Text for the primary call-to-action button (e.g. "Learn More").
           */
          ctaLabel?: string | null;
          /**
           * URL the CTA button links to (e.g. "/workshops/lakto").
           */
          ctaHref?: string | null;
          /**
           * Hex color for the central card background (e.g. "#555954").
           */
          panelColor?: string | null;
          /**
           * Hex color for the outer/page background (e.g. "#D2DFD7").
           */
          bgColor?: string | null;
          /**
           * Product or person image shown to the left of the central card.
           */
          leftImage?: (string | null) | Media;
          /**
           * Product or person image shown to the right of the central card.
           */
          rightImage?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
    /**
     * Each slide has a fullscreen image with overlay text and CTA.
     */
    slides?:
      | {
          /**
           * Fullscreen background for this slide.
           */
          image: string | Media;
          /**
           * Main heading on the slide.
           */
          title: string;
          /**
           * Elegant tagline below the title (e.g. "Elegance in Every Spoonful").
           */
          tagline?: string | null;
          /**
           * Optional supporting text.
           */
          description?: string | null;
          /**
           * CTA button text (e.g., "Order Now", "Learn More").
           */
          buttonLabel?: string | null;
          /**
           * Where the button links to.
           */
          buttonUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Content blocks. Leave empty for Voucher (slug: voucher) and Gastronomy (slug: gastronomy) pages.
   */
  layout?:
    | (
        | ContactBlock
        | CallToActionBlock
        | ContentBlock
        | FeatureCardsBlock
        | HeroBannerBlock
        | MediaBlock
        | ArchiveBlock
        | CarouselBlock
        | OurStoryBlock
        | ReadyToLearnCtaBlock
        | SponsorsBarBlock
        | TeamCardsBlock
        | TeamPreviewBlock
        | TestimonialsBlock
        | ThreeItemGridBlock
        | BannerBlock
        | FormBlock
        | VoucherCtaBlock
        | WorkshopSliderBlock
      )[]
    | null;
  /**
   * Content for the Gastronomy page (/gastronomy). Only applies when slug is "gastronomy".
   */
  gastronomy?: {
    /**
     * Main heading (e.g., "Elevate Your Gastronomy Business").
     */
    gastronomyHeroTitle?: string | null;
    /**
     * Button text (e.g., "Take a look").
     */
    gastronomyHeroCtaLabel: string;
    /**
     * Where the button links (e.g., "#offer").
     */
    gastronomyHeroCtaUrl?: string | null;
    /**
     * Heading above the offer cards (e.g., "What we offer").
     */
    gastronomyOfferSectionTitle?: string | null;
    /**
     * Three service cards.
     */
    gastronomyOfferCards?:
      | {
          image?: (string | null) | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    gastronomyQuoteText?: string | null;
    gastronomyQuoteSubtext?: string | null;
    gastronomyWorkshopSectionTitle: string;
    gastronomyWorkshopSectionSubtitle?: string | null;
    /**
     * Optional text below workshop subtitle explaining who can attend (e.g. chefs welcome, custom workshops available).
     */
    gastronomyWorkshopClarification?: string | null;
    /**
     * e.g. "Nächster Termin:" / "Next Appointment:"
     */
    gastronomyWorkshopNextDateLabel?: string | null;
    gastronomyWorkshopCards?:
      | {
          image?: (string | null) | Media;
          title: string;
          description: string;
          price: string;
          /**
           * e.g. "pro Person" / "per Person"
           */
          priceSuffix?: string | null;
          buttonLabel: string;
          buttonUrl: string;
          duration?: string | null;
          /**
           * e.g. "February 15, 2026"
           */
          nextDate?: string | null;
          id?: string | null;
        }[]
      | null;
    gastronomyOfferDetailsTitle?: string | null;
    gastronomyOfferDetails?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    gastronomyCollaborateImage?: (string | null) | Media;
    gastronomyCollaborateTitle: string;
    gastronomyCollaborateSubtitle?: string | null;
    gastronomyContactImage?: (string | null) | Media;
    gastronomyContactTitle: string;
    gastronomyContactDescription?: string | null;
    gastronomyFormPlaceholders?: {
      firstName?: string | null;
      lastName?: string | null;
      email?: string | null;
      message?: string | null;
    };
    gastronomySubjectOptions?: {
      default?: string | null;
      options?:
        | {
            label?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    gastronomySubmitButtonLabel?: string | null;
    gastronomyCtaBanner?: {
      heading?: string | null;
      description?: string | null;
      buttonLabel?: string | null;
      buttonHref?: string | null;
    };
    gastronomyMapEmbedUrl?: string | null;
  };
  /**
   * Content for the Gift Voucher page. These fields only apply when this page's slug is "voucher".
   */
  voucher?: {
    /**
     * Main headline above the voucher form (e.g. "Give the gift of fermentation").
     */
    heroHeading: string;
    /**
     * Short intro text below the heading explaining the voucher.
     */
    heroDescription: string;
    /**
     * List of amount options shown as buttons (e.g. 50€, 99€). Same in all languages.
     */
    voucherAmounts: {
      amount: string;
      id?: string | null;
    }[];
    /**
     * Ways to receive the voucher (e.g. by email or post).
     */
    deliveryOptions: {
      /**
       * Internal key, e.g. "email" or "post". Used for logic, not shown.
       */
      type: string;
      /**
       * Label shown to the user (e.g. "By email to print at home").
       */
      title: string;
      /**
       * Icon displayed next to this option.
       */
      icon: 'email' | 'card';
      id?: string | null;
    }[];
    /**
     * Logo displayed on the voucher preview card. Leave empty to use fallback.
     */
    cardLogo?: (string | null) | Media;
    /**
     * Label on the voucher preview card (e.g. "GIFT VOUCHER").
     */
    cardLabel: string;
    /**
     * Label above the amount on the card (e.g. "Voucher value").
     */
    valueLabel: string;
    /**
     * Small text under the amount (e.g. "Redeemable in our shop").
     */
    cardDisclaimer: string;
    /**
     * Label above the amount buttons (e.g. "VOUCHER VALUE").
     */
    amountSectionLabel: string;
    /**
     * Label above delivery options (e.g. "DELIVERY METHOD").
     */
    deliverySectionLabel: string;
    /**
     * Label for the optional greeting message field.
     */
    greetingLabel: string;
    /**
     * Placeholder text in the greeting textarea (e.g. "Max. 250 characters").
     */
    greetingPlaceholder: string;
    /**
     * Text for the main CTA button (e.g. "Add to cart").
     */
    addToCartButton: string;
    /**
     * Heading for the "Combine with Starter Set" section.
     */
    starterSetHeading: string;
    /**
     * Body text for the starter set section.
     */
    starterSetDescription: string;
    /**
     * Button text (e.g. "View Starter Sets").
     */
    starterSetButton: string;
    /**
     * Image shown in the starter set section. Leave empty to use fallback.
     */
    starterSetImage?: (string | null) | Media;
    /**
     * Heading for the "Gift for every occasion" section.
     */
    giftOccasionsHeading: string;
    /**
     * Occasion cards with image and caption (e.g. Birthdays, Weddings).
     */
    giftOccasions: {
      /**
       * Optional. Uses fallback if empty.
       */
      image?: (string | null) | Media;
      caption: string;
      id?: string | null;
    }[];
    /**
     * Heading above the voucher FAQ accordion.
     */
    faqHeading: string;
    /**
     * Frequently asked questions about vouchers.
     */
    faqs: {
      question: string;
      answer: string;
      id?: string | null;
    }[];
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  /**
   * When checked, the "For Chefs and Food Professionals" banner below the contact form is hidden.
   */
  hideCtaBanner?: boolean | null;
  /**
   * When checked, the map section below the contact form is hidden.
   */
  hideMap?: boolean | null;
  /**
   * When checked, the hero section is hidden. Use this when the page has a page-level hero (e.g. Food Presentation Slider).
   */
  hideHeroSection?: boolean | null;
  /**
   * Heading and subtext shown above the contact form.
   */
  hero: {
    /**
     * Full-width background for the hero. Leave empty for cream background.
     */
    image?: (string | null) | Media;
    /**
     * Main heading (e.g., "Kontakt" or "Get in Touch").
     */
    heading: string;
    /**
     * Optional supporting text below the heading.
     */
    subtext?: string | null;
    /**
     * Optional CTA button (e.g., "Explore Workshops").
     */
    buttonLabel?: string | null;
    /**
     * URL for the CTA button.
     */
    buttonHref?: string | null;
  };
  /**
   * Image displayed on the left side of the contact form card (e.g., team at workshop).
   */
  contactImage?: (string | null) | Media;
  contact: {
    /**
     * Heading above the form (e.g., "Kontakt").
     */
    heading: string;
    /**
     * Short intro text above the form fields.
     */
    description: string;
  };
  contactForm: {
    /**
     * Optional: Link to a Payload Form Builder form. If not set, a static form will be displayed.
     */
    form?: (string | null) | Form;
    placeholders: {
      /**
       * Placeholder for first name (e.g., "Vorname").
       */
      firstName: string;
      /**
       * Placeholder for last name (e.g., "Nachname").
       */
      lastName: string;
      /**
       * Placeholder for email field.
       */
      email: string;
      /**
       * Placeholder for message textarea.
       */
      message: string;
    };
    subjectOptions: {
      /**
       * Default option shown in subject dropdown (e.g., "Betreff").
       */
      default: string;
      options?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Text on the submit button (e.g., "Submit Now").
     */
    submitButton: string;
  };
  /**
   * Dark banner below the contact form (e.g., "For Chefs and Food Professionals").
   */
  ctaBanner: {
    /**
     * Main heading in golden accent (e.g., "For Chefs and Food Professionals").
     */
    heading: string;
    /**
     * Supporting text in white.
     */
    description: string;
    /**
     * CTA button text (e.g., "Get to know more here").
     */
    buttonLabel: string;
    /**
     * URL the button links to (e.g., "/gastronomy").
     */
    buttonHref: string;
  };
  /**
   * Google Maps embed URL (iframe src). Get from Google Maps → Share → Embed a map. Leave empty to hide map.
   */
  mapEmbedUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock".
 */
export interface FeatureCardsBlock {
  /**
   * Small uppercase text above the heading (e.g. "FERMENTATION").
   */
  eyebrow?: string | null;
  /**
   * Main section heading (e.g. "Why Fermentation?").
   */
  heading: string;
  /**
   * Short paragraph below the heading.
   */
  description?: string | null;
  /**
   * Cards with icon, title, and description. Shown in a horizontal row.
   */
  cards: {
    /**
     * Small icon displayed at the top of the card.
     */
    icon?: (string | null) | Media;
    /**
     * Title displayed below the icon (e.g. "Probiotics").
     */
    title: string;
    /**
     * Short description text for this feature.
     */
    description: string;
    id?: string | null;
  }[];
  /**
   * CTA button text (e.g. "Read more about it"). Leave empty to hide.
   */
  buttonLabel?: string | null;
  /**
   * URL the button links to.
   */
  buttonLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBannerBlock".
 */
export interface HeroBannerBlock {
  /**
   * Large white heading over the background image (e.g. "For Chefs and Food Professionals").
   */
  heading: string;
  /**
   * Subtext below the heading (1–2 sentences).
   */
  description: string;
  /**
   * CTA button text (e.g. "Get to know more here").
   */
  buttonLabel: string;
  /**
   * URL the CTA button links to.
   */
  buttonLink: string;
  /**
   * Full-width background image for the banner section. Used as fallback/poster when a video is set.
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Optional static video URL (e.g. /assets/videos/gastro-banner.mp4). Served from public/ — no DB or R2 storage used. Overrides the background image when set.
   */
  backgroundVideoUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurStoryBlock".
 */
export interface OurStoryBlock {
  /**
   * Small accent text above the heading (e.g. "Our Story", "Unsere Geschichte").
   */
  label: string;
  /**
   * Large heading for the story section.
   */
  heading: string;
  /**
   * Subheading text shown below the main heading.
   */
  subheading: string;
  /**
   * Body text paragraphs describing the story.
   */
  paragraphs: {
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'ourStory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadyToLearnCtaBlock".
 */
export interface ReadyToLearnCtaBlock {
  /**
   * CTA heading text (e.g. "Ready to learn?").
   */
  heading: string;
  /**
   * Body text below the heading.
   */
  description: string;
  primaryButton: {
    label: string;
    /**
     * URL the button links to (e.g. "/workshops").
     */
    href: string;
  };
  secondaryButton: {
    label: string;
    /**
     * URL the button links to (e.g. "/courses").
     */
    href: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'readyToLearnCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorsBarBlock".
 */
export interface SponsorsBarBlock {
  /**
   * Text above the logos (e.g. "This project is supported by:").
   */
  heading: string;
  /**
   * Sponsor/partner logos displayed in a horizontal row.
   */
  sponsors?:
    | {
        /**
         * Name used as alt text for the logo image.
         */
        name: string;
        /**
         * Sponsor logo. SVG or PNG recommended.
         */
        logo: string | Media;
        /**
         * Optional link to the sponsor website.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sponsorsBar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamCardsBlock".
 */
export interface TeamCardsBlock {
  /**
   * Small accent text above the heading (e.g. "Our Team").
   */
  label: string;
  /**
   * Main heading for the team section.
   */
  heading: string;
  /**
   * Team member cards with photo, name, role, and biography.
   */
  members: {
    /**
     * Team member portrait. If empty, a neutral placeholder is shown.
     */
    image?: (string | null) | Media;
    name: string;
    /**
     * Job title (e.g. "Fermentation Specialist & Chef").
     */
    role: string;
    /**
     * Short biography or description of the team member.
     */
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamPreviewBlock".
 */
export interface TeamPreviewBlock {
  /**
   * Small uppercase text above the heading (e.g. "Our Team").
   */
  eyebrow?: string | null;
  /**
   * Main heading (e.g. "Only The Best Instructors").
   */
  heading: string;
  /**
   * Body text describing the team.
   */
  description: string;
  /**
   * CTA button text (e.g. "About us").
   */
  buttonLabel?: string | null;
  /**
   * URL the button links to (e.g. "/about").
   */
  buttonLink?: string | null;
  /**
   * Team members to display. Typically 2 members with large portrait photos.
   */
  members: {
    name: string;
    /**
     * Role title (e.g. "Instructor").
     */
    role?: string | null;
    /**
     * Portrait photo. Tall aspect ratio recommended.
     */
    image?: (string | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamPreview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Small text above the heading (e.g. "Testimonials").
   */
  eyebrow?: string | null;
  /**
   * Section heading (e.g. "What They Like About Our Fermentation Class").
   */
  heading: string;
  /**
   * Optional "View All" button text. Leave empty to hide.
   */
  buttonLabel?: string | null;
  buttonLink?: string | null;
  /**
   * Individual testimonial entries displayed as a slider.
   */
  testimonials: {
    /**
     * The testimonial text.
     */
    quote: string;
    authorName: string;
    /**
     * Optional role/title of the author (e.g. "Artist").
     */
    authorRole?: string | null;
    /**
     * Star rating from 1 to 5.
     */
    rating?: number | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (string | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VoucherCtaBlock".
 */
export interface VoucherCtaBlock {
  /**
   * Large heading text (e.g. "Gift a special tasty experience").
   */
  heading: string;
  /**
   * Short paragraph below the heading (1–2 sentences).
   */
  description: string;
  /**
   * Text on the CTA button (e.g. "Voucher").
   */
  buttonLabel: string;
  /**
   * URL the button links to (e.g. "/voucher").
   */
  buttonLink: string;
  /**
   * Upload exactly 8 images for the bento gallery grid. They animate into a full-screen scrubbed gallery on scroll.
   */
  galleryImages?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'voucherCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkshopSliderBlock".
 */
export interface WorkshopSliderBlock {
  /**
   * Small uppercase text shown above each workshop slide (e.g. "Workshop Experience").
   */
  eyebrow?: string | null;
  /**
   * Add up to 6 workshop slides. Each slide has a title, description, features, image, and CTA.
   */
  workshops: {
    /**
     * Workshop name displayed as the main heading (e.g. "Lakto-Gemüse").
     */
    title: string;
    /**
     * Small label shown at the top of the info card (e.g. "For Chefs and Food Professionals").
     */
    audienceTag?: string | null;
    /**
     * Short description of the workshop (1–2 sentences).
     */
    description: string;
    /**
     * Visual theme for this slide. Light = ivory feature card with dark text. Dark = charcoal feature card with cream text.
     */
    theme?: ('light' | 'dark') | null;
    /**
     * Numbered feature list (e.g. "Duration: approx. 3 hours"). Shown with 01, 02, 03, … numbering.
     */
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * First workshop photo — shown full height in the gallery with the title overlay.
     */
    image?: (string | null) | Media;
    /**
     * Optional second photo shown alongside the first. Falls back to the primary image when not set.
     */
    image2?: (string | null) | Media;
    /**
     * URL the "Workshop Details" button links to (e.g. "/workshops/lakto-gemuese").
     */
    ctaLink?: string | null;
    /**
     * Label for the button linking to this workshop's detail page (e.g. "Workshop Details").
     */
    detailsButtonLabel?: string | null;
    id?: string | null;
  }[];
  /**
   * Label for the button linking to the main workshops page (e.g. "All Workshops").
   */
  allWorkshopsButtonLabel?: string | null;
  /**
   * URL the "All Workshops" button links to (default: "/workshops").
   */
  allWorkshopsLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'workshopSlider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: string | Product;
  options: (string | VariantOption)[];
  inventory?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (string | null) | User;
  customerEmail?: string | null;
  order?: (string | null) | Order;
  cart?: (string | null) | Cart;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (string | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer?: (string | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        eyebrow?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        showWordmark?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        heroImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        heroSlides?:
          | T
          | {
              slideId?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              attributes?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              panelColor?: T;
              bgColor?: T;
              leftImage?: T;
              rightImage?: T;
              id?: T;
            };
        media?: T;
        slides?:
          | T
          | {
              image?: T;
              title?: T;
              tagline?: T;
              description?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        contactBlock?: T | ContactBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        featureCards?: T | FeatureCardsBlockSelect<T>;
        heroBanner?: T | HeroBannerBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        ourStory?: T | OurStoryBlockSelect<T>;
        readyToLearnCta?: T | ReadyToLearnCtaBlockSelect<T>;
        sponsorsBar?: T | SponsorsBarBlockSelect<T>;
        teamCards?: T | TeamCardsBlockSelect<T>;
        teamPreview?: T | TeamPreviewBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        voucherCta?: T | VoucherCtaBlockSelect<T>;
        workshopSlider?: T | WorkshopSliderBlockSelect<T>;
      };
  gastronomy?:
    | T
    | {
        gastronomyHeroTitle?: T;
        gastronomyHeroCtaLabel?: T;
        gastronomyHeroCtaUrl?: T;
        gastronomyOfferSectionTitle?: T;
        gastronomyOfferCards?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        gastronomyQuoteText?: T;
        gastronomyQuoteSubtext?: T;
        gastronomyWorkshopSectionTitle?: T;
        gastronomyWorkshopSectionSubtitle?: T;
        gastronomyWorkshopClarification?: T;
        gastronomyWorkshopNextDateLabel?: T;
        gastronomyWorkshopCards?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              price?: T;
              priceSuffix?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              duration?: T;
              nextDate?: T;
              id?: T;
            };
        gastronomyOfferDetailsTitle?: T;
        gastronomyOfferDetails?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        gastronomyCollaborateImage?: T;
        gastronomyCollaborateTitle?: T;
        gastronomyCollaborateSubtitle?: T;
        gastronomyContactImage?: T;
        gastronomyContactTitle?: T;
        gastronomyContactDescription?: T;
        gastronomyFormPlaceholders?:
          | T
          | {
              firstName?: T;
              lastName?: T;
              email?: T;
              message?: T;
            };
        gastronomySubjectOptions?:
          | T
          | {
              default?: T;
              options?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
        gastronomySubmitButtonLabel?: T;
        gastronomyCtaBanner?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonLabel?: T;
              buttonHref?: T;
            };
        gastronomyMapEmbedUrl?: T;
      };
  voucher?:
    | T
    | {
        heroHeading?: T;
        heroDescription?: T;
        voucherAmounts?:
          | T
          | {
              amount?: T;
              id?: T;
            };
        deliveryOptions?:
          | T
          | {
              type?: T;
              title?: T;
              icon?: T;
              id?: T;
            };
        cardLogo?: T;
        cardLabel?: T;
        valueLabel?: T;
        cardDisclaimer?: T;
        amountSectionLabel?: T;
        deliverySectionLabel?: T;
        greetingLabel?: T;
        greetingPlaceholder?: T;
        addToCartButton?: T;
        starterSetHeading?: T;
        starterSetDescription?: T;
        starterSetButton?: T;
        starterSetImage?: T;
        giftOccasionsHeading?: T;
        giftOccasions?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        faqHeading?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  hideCtaBanner?: T;
  hideMap?: T;
  hideHeroSection?: T;
  hero?:
    | T
    | {
        image?: T;
        heading?: T;
        subtext?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  contactImage?: T;
  contact?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  contactForm?:
    | T
    | {
        form?: T;
        placeholders?:
          | T
          | {
              firstName?: T;
              lastName?: T;
              email?: T;
              message?: T;
            };
        subjectOptions?:
          | T
          | {
              default?: T;
              options?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
        submitButton?: T;
      };
  ctaBanner?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  mapEmbedUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock_select".
 */
export interface FeatureCardsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  buttonLabel?: T;
  buttonLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBannerBlock_select".
 */
export interface HeroBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttonLabel?: T;
  buttonLink?: T;
  backgroundImage?: T;
  backgroundVideoUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurStoryBlock_select".
 */
export interface OurStoryBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  subheading?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadyToLearnCtaBlock_select".
 */
export interface ReadyToLearnCtaBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  primaryButton?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryButton?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorsBarBlock_select".
 */
export interface SponsorsBarBlockSelect<T extends boolean = true> {
  heading?: T;
  sponsors?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamCardsBlock_select".
 */
export interface TeamCardsBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  members?:
    | T
    | {
        image?: T;
        name?: T;
        role?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamPreviewBlock_select".
 */
export interface TeamPreviewBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  buttonLabel?: T;
  buttonLink?: T;
  members?:
    | T
    | {
        name?: T;
        role?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  buttonLabel?: T;
  buttonLink?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorRole?: T;
        rating?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VoucherCtaBlock_select".
 */
export interface VoucherCtaBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttonLabel?: T;
  buttonLink?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkshopSliderBlock_select".
 */
export interface WorkshopSliderBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  workshops?:
    | T
    | {
        title?: T;
        audienceTag?: T;
        description?: T;
        theme?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        image2?: T;
        ctaLink?: T;
        detailsButtonLabel?: T;
        id?: T;
      };
  allWorkshopsButtonLabel?: T;
  allWorkshopsLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * The banner shown at the very top of the site. Use it to highlight promotions, events, or important messages.
   */
  announcementBar: {
    /**
     * Toggle the announcement bar on or off site-wide.
     */
    enabled?: boolean | null;
    /**
     * The message displayed in the announcement bar (e.g. "New workshops available!").
     */
    text: string;
    /**
     * URL the announcement links to (e.g. "/workshops"). Leave empty for no link.
     */
    link?: string | null;
  };
  /**
   * The main navigation links shown in the header. Drag to reorder. Each item can optionally have a dropdown with sub-items.
   */
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        /**
         * Optional sub-items shown in a dropdown menu. If empty, the nav item renders as a simple link.
         */
        dropdownItems?:
          | {
              label: string;
              href: string;
              /**
               * Short description shown below the label in the dropdown.
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Links shown in the "Quick Links" column.
   */
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Links shown in the "Our Workshops" column.
   */
  workshopLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Address displayed in the footer (e.g. "Grabenstraße 15, 8010 Graz, Austria").
   */
  location?: string | null;
  /**
   * Contact phone number.
   */
  phone?: string | null;
  /**
   * Heading for the newsletter section (e.g. "Subscribe Newsletter").
   */
  newsletterHeading?: string | null;
  /**
   * Short text above the newsletter subscribe form.
   */
  newsletterDescription?: string | null;
  socialMedia?: {
    facebook?: string | null;
    twitter?: string | null;
    pinterest?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        dropdownItems?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  workshopLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  location?: T;
  phone?: T;
  newsletterHeading?: T;
  newsletterDescription?: T;
  socialMedia?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        pinterest?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}